"""
TrackItRight — Classifier API

A small FastAPI service that loads the model trained in training.ipynb
and exposes it as a callable HTTP endpoint. This demonstrates the trained
classifier as a real, independently-runnable service, rather than only
existing inside a notebook.

Run with:
    uvicorn api:app --reload --port 8000

Then test with:
    http://localhost:8000/docs   (interactive API docs, auto-generated by FastAPI)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import joblib

app = FastAPI(
    title="TrackItRight Classifier API",
    description="Classifies a client message as deadline, task, or extra_work using a locally trained model.",
    version="1.0.0",
)

# Allow requests from the React frontend / Node backend during local development.
# In production, replace "*" with your actual frontend/backend URLs.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load the trained model and vectorizer once, when the server starts —
# not on every request, since loading from disk is relatively slow.
model = joblib.load("model.joblib")
vectorizer = joblib.load("vectorizer.joblib")


class MessageInput(BaseModel):
    text: str


class PredictionOutput(BaseModel):
    label: str
    confidence: float
    all_probabilities: dict


@app.get("/")
def root():
    return {"message": "TrackItRight Classifier API is running", "docs": "/docs"}


@app.post("/predict", response_model=PredictionOutput)
def predict(message: MessageInput):
    vec = vectorizer.transform([message.text])
    prediction = model.predict(vec)[0]

    # predict_proba gives the model's confidence for each possible label,
    # not just the single winning one — useful for showing "how sure" it is.
    probabilities = model.predict_proba(vec)[0]
    label_probabilities = dict(zip(model.classes_, probabilities.round(4)))
    confidence = float(max(probabilities))

    return {
        "label": prediction,
        "confidence": confidence,
        "all_probabilities": label_probabilities,
    }